/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
// import org.junit.platform.runner.JUnitPlatform;
// import org.junit.runner.RunWith;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
