/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import frido.mvnrepo.indexer.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
