package frido.mvnrepo.indexer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Crawler crawler = new Crawler();
        crawler.search("http://central.maven.org/maven2/activesoap/");
    }
}
