package frido.mvnrepo.indexer;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App2 {

    static Logger log = LoggerFactory.getLogger(App2.class);
    
    public static void main(String[] args) {
        Database database = new MongoDatabase();
        Executor executor = Executors.newFixedThreadPool(2);
        Client httpClient = new UrlClient(new JerseyHttpClient());
        Consumer pomHandler = new PomHandler(database);
        Downloader downloader = new Downloader(executor, httpClient, pomHandler);
        database.getAll("metadata").forEach(metadata -> {
			try { // TODO: not everything in try
                String pomUrl;
                pomUrl = new Artifact(metadata).getPomUrl();
                downloader.start(pomUrl);
			} catch (Exception e) {
                log.error("Artifact - PomUrl", e);
			}
            
        });
    }
}
