package frido.mvnrepo.indexer;

import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.bson.Document;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App2 {

    Logger log = LoggerFactory.getLogger(App2.class);
    
    private static final String ENV_MONGO_URL = "MONGO_URL";
    
    private Mongo mongo;

    private Set<String> projectLinks = new HashSet<String>();

    //TODO: file properties, env, params?
    private Map<String, String> getProperties(){
        Map<String, String> env = System.getenv();
        return env;
    }

    public App2(){
        String connectionString = getProperties().get(ENV_MONGO_URL);
        this.mongo = new Mongo(connectionString);
    }

    /** 
     * Run main application.
     */
    public static void main(String[] args) {
        App2 app = new App2();
        app.run();
    }

    static int counter = 0;
    public void run(){
        Downloader downloader = new Downloader();
        this.mongo.getAll("metadata").forEach(doc -> {
            downloader.start(doc);
        });
    }

    

	
}
