package frido.mvnrepo.indexer;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App3 {

    Logger log = LoggerFactory.getLogger(App3.class);

    public static void main(String[] args) {
        Executor executor = Executors.newFixedThreadPool(5);
        Database database = new MongoDatabase();
        Consumer consumer = new GitHubHandler(database);
        Client httpClient = new GitHubClient(new JerseyHttpClient("frido", System.getenv().get("GITHUB_KEY")));
        GitHubLoader loader = new GitHubLoader(executor, consumer, httpClient);
        database.getGitHubRelated().forEach(doc -> {
            loader.start(doc.getString("projectUrl"));
        });
    }
}
